[package]
name = "repodeck-desktop"
version = "0.1.1-preview.3"
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
repodeck-core = { path = "../crates/core" }
serde = { version = "1", features = ["derive"] }
rfd = "0.17.2"
open = "5"

[dev-dependencies]
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_Security"] }
