const { chromium } = require('playwright');
const fs = require('node:fs/promises');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => {
    const settings = { schemaVersion: 1, onboardingCompleted: true, workspaces: [{ id: 'fixture', name: 'Commerce Platform', rootPath: 'C:/Projects/commerce' }], theme: 'light', maxDepth: 12, maxEntries: 50000, excluded: ['.git'], showHidden: false, editor: 'code' };
    const status = (name, changes) => ({ relativePath: name, error: null, status: { path: `C:/Projects/commerce/${name}`, branch: 'feature/checkout', detached: false, upstream: 'origin/main', ahead: 2, behind: 0, remotes: [`https://github.com/example/${name}.git`], changes } });
    const snapshot = { entries: [{ path: 'AGENTS.md', directory: false, agentConfig: true, repository: false, size: 150, modifiedMs: 0 }], warnings: [], repositories: [status('storefront', [{ path: 'src/checkout.ts', index: ' ', worktree: 'M', originalPath: null }]), status('payments-api', []), status('shared-components', [])] };
    snapshot.repositories.push({ relativePath: 'private-service', status: null, error: 'Repository unavailable' });
    snapshot.repositories.push({ relativePath: 'unknown-service', status: null, error: null });
    const longRepository = status('packages/shared-platform-infrastructure', []);
    longRepository.status.branch = 'feature/' + 'long-branch-segment-'.repeat(12);
    longRepository.status.ahead = 123456;
    snapshot.repositories.push(longRepository);
    snapshot.entries.push({ path: 'docs', directory: true, agentConfig: false, repository: false, size: 0, modifiedMs: 0 }, { path: 'docs/guide.md', directory: false, agentConfig: false, repository: false, size: 50, modifiedMs: 0 });
    snapshot.entries.forEach(entry => entry.modifiedMs = Date.UTC(2026, 8, 11, 10, 20));
    let callbackId = 0;
    window.__TAURI_INTERNALS__ = { transformCallback: () => ++callbackId, unregisterCallback: () => {}, invoke: async (command) => {
      if (command === 'check_git') return { available: true, platform: 'windows', message: 'Fixture Git available' };
      if (command === 'get_settings') return settings;
      if (command === 'save_settings') return new Promise((_, reject) => {
        window.__rejectSettingsSave = () => reject(new Error('Fixture disk unavailable'));
      });
      if (command === 'watch_workspace' || command === 'stop_watch') return null;
      if (command === 'scan_workspace') return snapshot;
      if (command === 'file_diff') return '@@ -12,2 +12,2 @@\n-const timeout = 1000;\n+const timeout = 3000;';
      if (command === 'preview_file') return { kind: 'text', content: '# Project instructions\n\nRun the tests before changing shared interfaces.' };
      throw new Error(`Unexpected command: ${command}`);
    } };
  });
  await fs.mkdir('.tools/screenshots', { recursive: true });
  for (const [width, height] of [[1280, 820], [800, 600], [600, 800]]) {
    await page.setViewportSize({ width, height });
    await page.goto('http://127.0.0.1:1420');
    await page.getByRole('region', { name: 'Workspace summary' }).getByText('2 unavailable').waitFor();
    const ordinary = page.getByRole('button', { name: /^shared-components/ });
    if (!(await ordinary.locator('strong').evaluate(el => el.getBoundingClientRect().height < 25))) throw new Error(`Ordinary repository name breaks across lines at ${width}`);
    const longRow = page.getByRole('button', { name: /^shared-platform/ });
    await longRow.click();
    const branch = longRow.locator('.repo-name small > span');
    if (await branch.getAttribute('title') !== await branch.textContent()) throw new Error('Truncated branch does not expose its full value');
    if (!(await page.locator('.repo-row').evaluateAll(rows => rows.every(row => {
      const name = row.querySelector('.repo-name').getBoundingClientRect();
      const status = row.lastElementChild.getBoundingClientRect();
      return name.bottom <= status.top && row.scrollWidth <= row.clientWidth;
    })))) throw new Error(`Repository name and status overlap or overflow at ${width}`);
    if (!(await longRow.evaluate(el => el.scrollWidth <= el.clientWidth))) throw new Error(`Long repository row overflows at ${width}`);
    if (!(await page.getByRole('region', { name: 'Inspector' }).evaluate(el => el.scrollWidth <= el.clientWidth))) throw new Error(`Long branch inspector overflows at ${width}`);
    await page.screenshot({ path: `.tools/screenshots/long-repository-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: /^unknown-service/ }).click();
    const inspector = page.getByRole('region', { name: 'Inspector' });
    await inspector.getByText('Repository status unavailable.', { exact: true }).waitFor();
    if (/Detached HEAD|ahead|behind/.test(await inspector.innerText())) throw new Error('Unavailable inspection shows branch data');
    if (await inspector.getByRole('button', { name: 'Hooks and LFS' }).count()) throw new Error('Unavailable inspection shows Git tools');
    if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error(`Unavailable inspection overflows at ${width}`);
    await page.screenshot({ path: `.tools/screenshots/unavailable-${width}.png`, fullPage: true });
    await page.getByRole('textbox', { name: 'Filter workspace' }).fill('no-match');
    await page.getByText('No repositories match your filter.', { exact: true }).waitFor();
    await page.getByRole('textbox', { name: 'Filter workspace' }).fill('');
    await page.getByRole('button', { name: /storefront.*feature/ }).click();
    await page.getByRole('tab', { name: 'Repositories', exact: true }).focus();
    await page.keyboard.press('ArrowRight');
    await page.getByRole('tabpanel', { name: 'Files', exact: true }).waitFor();
    await page.keyboard.press('Home');
    await page.getByRole('tabpanel', { name: 'Repositories', exact: true }).waitFor();
    await page.getByRole('button', { name: /src\/checkout.ts/ }).click();
    await page.getByText('+const timeout = 3000;', { exact: false }).waitFor();
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
    if (overflow) throw new Error(`Horizontal document overflow at ${width}`);
    await page.screenshot({ path: `.tools/screenshots/workspace-${width}.png`, fullPage: true });
    await page.getByRole('tab', { name: 'Files', exact: true }).click();
    await page.getByRole('button', { name: /docs, 1 files; 50 B/ }).click();
    await page.getByRole('button', { name: /docs\/guide.md/ }).click();
    await page.locator('pre').filter({ hasText: 'Project instructions' }).waitFor();
    if (await page.locator('.file-row[aria-current="true"]').count() !== 1) throw new Error('Selected file is not identified');
    if (!(await page.locator('time[datetime="2026-09-11T10:20:00.000Z"]').count())) throw new Error('Modified dates are missing');
    if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error(`File metadata overflows at ${width}`);
    await page.screenshot({ path: `.tools/screenshots/tree-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    if (!(await page.getByRole('button', { name: 'Close settings' }).evaluate(el => el === document.activeElement))) throw new Error('Settings did not receive focus');
    await page.keyboard.press('Shift+Tab');
    if (!(await page.getByRole('button', { name: 'Save settings' }).evaluate(el => el === document.activeElement))) throw new Error('Settings focus escaped');
    await page.keyboard.press('Escape');
    if (await page.getByRole('dialog').count()) throw new Error('Escape did not close settings');
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    await page.getByRole('button', { name: 'Save settings' }).click();
    const modal = page.getByRole('dialog');
    if (!(await modal.evaluate(el => el === document.activeElement && [...el.querySelectorAll('input, select, textarea, button')].every(control => control.disabled)))) throw new Error('Pending save does not lock controls and retain focus');
    await page.keyboard.press('Escape');
    await page.keyboard.press('Tab');
    if (!(await modal.evaluate(el => el === document.activeElement))) throw new Error('Pending save focus escaped');
    await page.screenshot({ path: `.tools/screenshots/settings-saving-${width}.png`, fullPage: true });
    await page.evaluate(() => window.__rejectSettingsSave());
    await modal.getByRole('alert').filter({ hasText: 'Fixture disk unavailable' }).waitFor();
    if (!(await page.getByRole('button', { name: 'Save settings' }).isEnabled())) throw new Error('Failed save cannot be retried');
    await page.keyboard.press('Tab');
    if (!(await page.getByRole('button', { name: 'Close settings' }).evaluate(el => el === document.activeElement))) throw new Error('Focus did not return to enabled controls');
    await page.keyboard.press('Escape');
  }
  if (errors.length) throw new Error(errors.join('\n'));
  await browser.close();
  console.log('UI fixture: repository/diff, folder expansion, file preview, settings keyboard focus at 1280, 800 and 600px; zero page errors.');
})().catch(error => { console.error(error); process.exit(1); });
